//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 01:05:25 PM CEST 
//


package org.eclipse.emf.ecore.jaxbmodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EPackage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EPackage">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.eclipse.org/emf/2002/Ecore}ENamedElement">
 *       &lt;sequence>
 *         &lt;element name="eClassifiers" type="{http://www.eclipse.org/emf/2002/Ecore}EClassifier" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="eSubpackages" type="{http://www.eclipse.org/emf/2002/Ecore}EPackage" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="nsURI" type="{http://www.eclipse.org/emf/2002/Ecore}EString" />
 *       &lt;attribute name="nsPrefix" type="{http://www.eclipse.org/emf/2002/Ecore}EString" />
 *       &lt;attribute name="eFactoryInstance" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EPackage", propOrder = {
    "eClassifiers",
    "eSubpackages"
})
public class EPackage
    extends ENamedElement
{

    protected List<EClassifier> eClassifiers;
    protected List<EPackage> eSubpackages;
    @XmlAttribute(name = "nsURI")
    protected String nsURI;
    @XmlAttribute(name = "nsPrefix")
    protected String nsPrefix;
    @XmlAttribute(name = "eFactoryInstance")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object eFactoryInstance;

    /**
     * Gets the value of the eClassifiers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eClassifiers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEClassifiers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EClassifier }
     * 
     * 
     */
    public List<EClassifier> getEClassifiers() {
        if (eClassifiers == null) {
            eClassifiers = new ArrayList<EClassifier>();
        }
        return this.eClassifiers;
    }

    /**
     * Gets the value of the eSubpackages property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eSubpackages property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getESubpackages().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EPackage }
     * 
     * 
     */
    public List<EPackage> getESubpackages() {
        if (eSubpackages == null) {
            eSubpackages = new ArrayList<EPackage>();
        }
        return this.eSubpackages;
    }

    /**
     * Gets the value of the nsURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNsURI() {
        return nsURI;
    }

    /**
     * Sets the value of the nsURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNsURI(String value) {
        this.nsURI = value;
    }

    /**
     * Gets the value of the nsPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNsPrefix() {
        return nsPrefix;
    }

    /**
     * Sets the value of the nsPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNsPrefix(String value) {
        this.nsPrefix = value;
    }

    /**
     * Gets the value of the eFactoryInstance property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getEFactoryInstance() {
        return eFactoryInstance;
    }

    /**
     * Sets the value of the eFactoryInstance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setEFactoryInstance(Object value) {
        this.eFactoryInstance = value;
    }

}
