//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 01:05:25 PM CEST 
//

package org.eclipse.emf.ecore.jaxbmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EStructuralFeature")
@XmlSeeAlso({EAttribute.class, EReference.class})
public abstract class EStructuralFeature extends ETypedElement {

    @XmlAttribute(name = "changeable")
    protected String changeable;
    @XmlAttribute(name = "volatile")
    protected String _volatile;
    @XmlAttribute(name = "transient")
    protected String _transient;
    @XmlAttribute(name = "defaultValueLiteral")
    protected String defaultValueLiteral;
    @XmlAttribute(name = "defaultValue")
    protected String defaultValue;
    @XmlAttribute(name = "unsettable")
    protected String unsettable;
    @XmlAttribute(name = "derived")
    protected String derived;

    public String getChangeable() {
        if (changeable == null) {
            return "true";
        } else {
            return changeable;
        }
    }

    public void setChangeable(String value) {
        this.changeable = value;
    }

    public String getVolatile() {
        return _volatile;
    }

    public void setVolatile(String value) {
        this._volatile = value;
    }

    public String getTransient() {
        return _transient;
    }

    public void setTransient(String value) {
        this._transient = value;
    }

    public String getDefaultValueLiteral() {
        return defaultValueLiteral;
    }

    public void setDefaultValueLiteral(String value) {
        this.defaultValueLiteral = value;
    }

    public String getDefaultValue() {
        return defaultValue;
    }

    public void setDefaultValue(String value) {
        this.defaultValue = value;
    }

    public String getUnsettable() {
        return unsettable;
    }

    public void setUnsettable(String value) {
        this.unsettable = value;
    }

    public String getDerived() {
        return derived;
    }

    public void setDerived(String value) {
        this.derived = value;
    }
}
