//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 01:05:25 PM CEST 
//

package org.eclipse.emf.ecore.jaxbmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ETypedElement", propOrder = {"eGenericType"})
@XmlSeeAlso({EParameter.class, EOperation.class, EStructuralFeature.class})
public abstract class ETypedElement extends ENamedElement {

    protected EGenericType eGenericType;
    @XmlAttribute(name = "ordered")
    protected String ordered;
    @XmlAttribute(name = "unique")
    protected String unique;
    @XmlAttribute(name = "lowerBound")
    protected String lowerBound;
    @XmlAttribute(name = "upperBound")
    protected String upperBound;
    @XmlAttribute(name = "many")
    protected String many;
    @XmlAttribute(name = "required")
    protected String required;
    @XmlAttribute(name = "eType")
    @XmlSchemaType(name = "anyURI")
    protected String eType;

    public EGenericType getEGenericType() {
        return eGenericType;
    }

    public void setEGenericType(EGenericType value) {
        this.eGenericType = value;
    }

    public String getOrdered() {
        if (ordered == null) {
            return "true";
        } else {
            return ordered;
        }
    }

    public void setOrdered(String value) {
        this.ordered = value;
    }

    public String getUnique() {
        if (unique == null) {
            return "true";
        } else {
            return unique;
        }
    }

    public void setUnique(String value) {
        this.unique = value;
    }

    public String getLowerBound() {
        return lowerBound;
    }

    public void setLowerBound(String value) {
        this.lowerBound = value;
    }

    public String getUpperBound() {
        if (upperBound == null) {
            return "1";
        } else {
            return upperBound;
        }
    }

    public void setUpperBound(String value) {
        this.upperBound = value;
    }

    public String getMany() {
        return many;
    }

    public void setMany(String value) {
        this.many = value;
    }

    public String getRequired() {
        return required;
    }

    public void setRequired(String value) {
        this.required = value;
    }

    public String getEType() {
        return eType;
    }

    public void setEType(String value) {
        this.eType = value;
    }
}
