// Tell Jenkins how to build projects from this repository
pipeline {
	agent {
		label 'magicdraw19'
	} 
	parameters {
		string(name: 'RELEASE_VERSION', defaultValue: '', 
			description: 'Set this parameter to update the project version version accordingly, should be used to remove -SNAPSHOT from version numbers. Leave it empty to keep version from the repository.')
	}
	// Keep only the last 5 builds
	options {
		buildDiscarder(logRotator(numToKeepStr: '5'))
	}
	environment {
		VERSION_STRINGS = " ${params.RELEASE_VERSION ? '-Pversion=' + params.RELEASE_VERSION : ''} "
	}
	
	tools { 
		maven 'Maven 3.3.9' 
		jdk 'OpenJDK 8' 
	}

	stages {
		stage('Build Plug-in') { 
			steps {
				dir ('.'){
					sh "./gradlew clean"
					sh "./gradlew ${VERSION_STRINGS} assemble"
				}
			}
		}
		stage('Deploy Plugin') {
			when {branch "master"} 
			steps {
				withCredentials([usernamePassword(credentialsId: 'nexus-buildserver-deploy', passwordVariable: 'DEPLOY_PASSWORD', usernameVariable: 'DEPLOY_USER')]) {
					script{
					    dir ('.') {
                    			sh "./gradlew ${VERSION_STRINGS} bundle"
					    }
					}
				}
			}
		}
	}

	post {
		always {
			archiveArtifacts artifacts: './build/*.zip', onlyIfSuccessful: true
		}
	}
}
