//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 01:05:25 PM CEST 
//


package org.eclipse.emf.ecore.jaxbmodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EClassifier complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EClassifier">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.eclipse.org/emf/2002/Ecore}ENamedElement">
 *       &lt;sequence>
 *         &lt;element name="eTypeParameters" type="{http://www.eclipse.org/emf/2002/Ecore}ETypeParameter" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="instanceClassName" type="{http://www.eclipse.org/emf/2002/Ecore}EString" />
 *       &lt;attribute name="instanceClass" type="{http://www.eclipse.org/emf/2002/Ecore}EJavaClass" />
 *       &lt;attribute name="defaultValue" type="{http://www.eclipse.org/emf/2002/Ecore}EJavaObject" />
 *       &lt;attribute name="instanceTypeName" type="{http://www.eclipse.org/emf/2002/Ecore}EString" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EClassifier", propOrder = {
    "eTypeParameters"
})
@XmlSeeAlso({
    EDataType.class,
    EClass.class
})
public abstract class EClassifier
    extends ENamedElement
{

    protected List<ETypeParameter> eTypeParameters;
    @XmlAttribute(name = "instanceClassName")
    protected String instanceClassName;
    @XmlAttribute(name = "instanceClass")
    protected String instanceClass;
    @XmlAttribute(name = "defaultValue")
    protected String defaultValue;
    @XmlAttribute(name = "instanceTypeName")
    protected String instanceTypeName;

    /**
     * Gets the value of the eTypeParameters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eTypeParameters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getETypeParameters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ETypeParameter }
     * 
     * 
     */
    public List<ETypeParameter> getETypeParameters() {
        if (eTypeParameters == null) {
            eTypeParameters = new ArrayList<ETypeParameter>();
        }
        return this.eTypeParameters;
    }

    /**
     * Gets the value of the instanceClassName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstanceClassName() {
        return instanceClassName;
    }

    /**
     * Sets the value of the instanceClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstanceClassName(String value) {
        this.instanceClassName = value;
    }

    /**
     * Gets the value of the instanceClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstanceClass() {
        return instanceClass;
    }

    /**
     * Sets the value of the instanceClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstanceClass(String value) {
        this.instanceClass = value;
    }

    /**
     * Gets the value of the defaultValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultValue() {
        return defaultValue;
    }

    /**
     * Sets the value of the defaultValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultValue(String value) {
        this.defaultValue = value;
    }

    /**
     * Gets the value of the instanceTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstanceTypeName() {
        return instanceTypeName;
    }

    /**
     * Sets the value of the instanceTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstanceTypeName(String value) {
        this.instanceTypeName = value;
    }

}
