//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 01:05:25 PM CEST 
//


package org.eclipse.emf.ecore.jaxbmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EFactory complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EFactory">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.eclipse.org/emf/2002/Ecore}EModelElement">
 *       &lt;attribute name="ePackage" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EFactory")
public class EFactory
    extends EModelElement
{

    @XmlAttribute(name = "ePackage")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object ePackage;

    /**
     * Gets the value of the ePackage property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getEPackage() {
        return ePackage;
    }

    /**
     * Sets the value of the ePackage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setEPackage(Object value) {
        this.ePackage = value;
    }

}
