//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 01:05:25 PM CEST 
//


package org.eclipse.emf.ecore.jaxbmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EStructuralFeature complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EStructuralFeature">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.eclipse.org/emf/2002/Ecore}ETypedElement">
 *       &lt;attribute name="changeable" type="{http://www.eclipse.org/emf/2002/Ecore}EBoolean" default="true" />
 *       &lt;attribute name="volatile" type="{http://www.eclipse.org/emf/2002/Ecore}EBoolean" />
 *       &lt;attribute name="transient" type="{http://www.eclipse.org/emf/2002/Ecore}EBoolean" />
 *       &lt;attribute name="defaultValueLiteral" type="{http://www.eclipse.org/emf/2002/Ecore}EString" />
 *       &lt;attribute name="defaultValue" type="{http://www.eclipse.org/emf/2002/Ecore}EJavaObject" />
 *       &lt;attribute name="unsettable" type="{http://www.eclipse.org/emf/2002/Ecore}EBoolean" />
 *       &lt;attribute name="derived" type="{http://www.eclipse.org/emf/2002/Ecore}EBoolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EStructuralFeature")
@XmlSeeAlso({
    EAttribute.class,
    EReference.class
})
public abstract class EStructuralFeature
    extends ETypedElement
{

    @XmlAttribute(name = "changeable")
    protected String changeable;
    @XmlAttribute(name = "volatile")
    protected String _volatile;
    @XmlAttribute(name = "transient")
    protected String _transient;
    @XmlAttribute(name = "defaultValueLiteral")
    protected String defaultValueLiteral;
    @XmlAttribute(name = "defaultValue")
    protected String defaultValue;
    @XmlAttribute(name = "unsettable")
    protected String unsettable;
    @XmlAttribute(name = "derived")
    protected String derived;

    /**
     * Gets the value of the changeable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChangeable() {
        if (changeable == null) {
            return "true";
        } else {
            return changeable;
        }
    }

    /**
     * Sets the value of the changeable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChangeable(String value) {
        this.changeable = value;
    }

    /**
     * Gets the value of the volatile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVolatile() {
        return _volatile;
    }

    /**
     * Sets the value of the volatile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVolatile(String value) {
        this._volatile = value;
    }

    /**
     * Gets the value of the transient property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransient() {
        return _transient;
    }

    /**
     * Sets the value of the transient property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransient(String value) {
        this._transient = value;
    }

    /**
     * Gets the value of the defaultValueLiteral property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultValueLiteral() {
        return defaultValueLiteral;
    }

    /**
     * Sets the value of the defaultValueLiteral property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultValueLiteral(String value) {
        this.defaultValueLiteral = value;
    }

    /**
     * Gets the value of the defaultValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultValue() {
        return defaultValue;
    }

    /**
     * Sets the value of the defaultValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultValue(String value) {
        this.defaultValue = value;
    }

    /**
     * Gets the value of the unsettable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnsettable() {
        return unsettable;
    }

    /**
     * Sets the value of the unsettable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnsettable(String value) {
        this.unsettable = value;
    }

    /**
     * Gets the value of the derived property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDerived() {
        return derived;
    }

    /**
     * Sets the value of the derived property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDerived(String value) {
        this.derived = value;
    }

}
