//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 01:05:25 PM CEST 
//


package org.eclipse.emf.ecore.jaxbmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ETypedElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ETypedElement">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.eclipse.org/emf/2002/Ecore}ENamedElement">
 *       &lt;sequence>
 *         &lt;element name="eGenericType" type="{http://www.eclipse.org/emf/2002/Ecore}EGenericType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ordered" type="{http://www.eclipse.org/emf/2002/Ecore}EBoolean" default="true" />
 *       &lt;attribute name="unique" type="{http://www.eclipse.org/emf/2002/Ecore}EBoolean" default="true" />
 *       &lt;attribute name="lowerBound" type="{http://www.eclipse.org/emf/2002/Ecore}EInt" />
 *       &lt;attribute name="upperBound" type="{http://www.eclipse.org/emf/2002/Ecore}EInt" default="1" />
 *       &lt;attribute name="many" type="{http://www.eclipse.org/emf/2002/Ecore}EBoolean" />
 *       &lt;attribute name="required" type="{http://www.eclipse.org/emf/2002/Ecore}EBoolean" />
 *       &lt;attribute name="eType" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ETypedElement", propOrder = {
    "eGenericType"
})
@XmlSeeAlso({
    EParameter.class,
    EOperation.class,
    EStructuralFeature.class
})
public abstract class ETypedElement
    extends ENamedElement
{

    protected EGenericType eGenericType;
    @XmlAttribute(name = "ordered")
    protected String ordered;
    @XmlAttribute(name = "unique")
    protected String unique;
    @XmlAttribute(name = "lowerBound")
    protected String lowerBound;
    @XmlAttribute(name = "upperBound")
    protected String upperBound;
    @XmlAttribute(name = "many")
    protected String many;
    @XmlAttribute(name = "required")
    protected String required;
    @XmlAttribute(name = "eType")
    @XmlSchemaType(name = "anyURI")
    protected String eType;

    /**
     * Gets the value of the eGenericType property.
     * 
     * @return
     *     possible object is
     *     {@link EGenericType }
     *     
     */
    public EGenericType getEGenericType() {
        return eGenericType;
    }

    /**
     * Sets the value of the eGenericType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EGenericType }
     *     
     */
    public void setEGenericType(EGenericType value) {
        this.eGenericType = value;
    }

    /**
     * Gets the value of the ordered property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrdered() {
        if (ordered == null) {
            return "true";
        } else {
            return ordered;
        }
    }

    /**
     * Sets the value of the ordered property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrdered(String value) {
        this.ordered = value;
    }

    /**
     * Gets the value of the unique property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnique() {
        if (unique == null) {
            return "true";
        } else {
            return unique;
        }
    }

    /**
     * Sets the value of the unique property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnique(String value) {
        this.unique = value;
    }

    /**
     * Gets the value of the lowerBound property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLowerBound() {
        return lowerBound;
    }

    /**
     * Sets the value of the lowerBound property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLowerBound(String value) {
        this.lowerBound = value;
    }

    /**
     * Gets the value of the upperBound property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpperBound() {
        if (upperBound == null) {
            return "1";
        } else {
            return upperBound;
        }
    }

    /**
     * Sets the value of the upperBound property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpperBound(String value) {
        this.upperBound = value;
    }

    /**
     * Gets the value of the many property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMany() {
        return many;
    }

    /**
     * Sets the value of the many property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMany(String value) {
        this.many = value;
    }

    /**
     * Gets the value of the required property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequired() {
        return required;
    }

    /**
     * Sets the value of the required property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequired(String value) {
        this.required = value;
    }

    /**
     * Gets the value of the eType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEType() {
        return eType;
    }

    /**
     * Sets the value of the eType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEType(String value) {
        this.eType = value;
    }

}
