//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.08 at 01:05:25 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.eclipse.org/emf/2002/Ecore")
package org.eclipse.emf.ecore.jaxbmodel;
